version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: dev.Dockerfile
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  mysql:
    image: mysql:8.0.41
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 8s
      interval: 2s
      timeout: 4s
      retries: 3



volumes:
  mysql_data: