version: '3.8'

services:
  app:
    image: 905418185177.dkr.ecr.eu-west-3.amazonaws.com/backend-api:${IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD:${DB_PASSWORD}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
  mysql:
    image: mysql:8.0.41
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 3
    restart: unless-stopped



volumes:
  mysql_data: